spring:
  application:
    name: activity-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}


rabbitmq:
  queue:
    name: activity_queue
  exchange:
    name: activity_exchange
  routing:
    key: activity_routing_key
